steps:
  install:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm install
  lint-js:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: install
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: install
    commands:
      - npm run lint:hbs
  # Enable once we are on a version with css linting
  # lint-css:
  #   image: danlynn/ember-cli:5.8.0-node_20.12
  #   depends_on: install
  #   commands:
  #     - npm run lint:css
  # Enable once we are on a version with a standalone Prettier setup
  # lint-formatting:
  #   image: danlynn/ember-cli:5.8.0-node_20.12
  #   depends_on: install
  #   commands:
  #     - npm run lint:format
  dependency-lint:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: install
    failure: ignore
    commands:
      - ember dependency-lint
  test:
    image: danlynn/ember-cli:5.8.0-node_20.12
    depends_on: [lint-js, lint-hbs, dependency-lint]
    commands:
      - npm run test:ember
when:
  - event: pull_request
